### PR TITLE
Features/better cache mgmt

### LINKED ISSUE #118: Making CachingStrategy available in Cache
### Description

I'd like to add the caching strategy to the debug toolbar, I think it's one of the most critical pieces of information.  Related to #117  and #113

image

### Example

Perhaps when we implement the CacheInterface with the common methods, we could add a getCacheStrategy().  But I could be completely wrong about where the strategy is defined.

### LINKED ISSUE #125: page_cache requires a regex, even if url provided
### Version(s) affected

1.1.x

### Description

The page_cache: has been changed to page_caches, and takes an array of page_cache.

But simply changing the example of what's listed in the documentation doesn't work, because it requires a cache_name and regex key.   Both should have sensible defaults.  

### How to reproduce

```yaml
        workbox:
            page_caches:
                - 
                    cache_name: staleWhileRevalidate # maybe make this the strategy name by default?
                    strategy: 'staleWhileRevalidate'
                    broadcast: true
                    broadcast_headers:
                        - 'X-App-Cache'
                    regex: / # what should this be
                    urls:
                    - 'app_homepage'
```

### Possible Solution

The demo and documentation both need to be updated to the latest version of 1.1.x

```yaml
workbox:
            page_cache:
                strategy: 'staleWhileRevalidate'
                broadcast: true
                broadcast_headers:
                    - 'X-App-Cache'
                urls:
                - 'app_homepage'
```

### Additional Context

_No response_

### LINKED ISSUE #126: Support Range Responses
### Description

The `page_caches` config should have an option to support range responses as described here: https://developer.chrome.com/docs/workbox/modules/workbox-range-requests

### Example

_No response_

### LINKED ISSUE #129: allow maxAge to be configured with human-readable strings
### Description

Since PHP will [parse standard time strings](https://www.php.net/manual/en/function.strtotime.php), instead of converting maxAge to something human readable in the debug toolbar, what about putting the human-readable string in the yaml.

### Example

```yaml
pwa:
    serviceworker:
        enabled: true
        src: "sw.js"
        workbox:
            image_cache:
                enabled: true
#                max_age: 2_592_000 # 30 days
                max_age: 30 days
                max_entries: 200
                regex: '/\.(png|jpe?g|svg|webp)$/'
```

### LINKED ISSUE #132: Custom Rules should come after generated rules
### Version(s) affected

1.1.x

### Description

Until I can figure out how to map rules to the pwa.yaml, I'm just adding them as custom rules.  These come from the PWA-IndexedDB tutorial, their sw.js is at https://github.com/paritoshtripathi/PWA-Sample-IndexedDB/blob/master/solution/app/sw.js
and I'm trying to re-create the application without custom javascript.

```js
  workbox.precaching.precacheAndRoute([]);

  const showNotification = () => {
    self.registration.showNotification('Background sync success!', {
      body: '🎉`🎉`🎉`'
    });
  };

  const bgSyncPlugin = new workbox.backgroundSync.Plugin(
    'dashboardr-queue',
    {
      callbacks: {
        queueDidReplay: showNotification
        // other types of callbacks could go here
      }
    }
  );

  const networkWithBackgroundSync = new workbox.strategies.NetworkOnly({
    plugins: [bgSyncPlugin],
  });

  workbox.routing.registerRoute(
    /\/api\/add/,
    networkWithBackgroundSync,
    'POST'
  );
```

### How to reproduce

Add the above the sw.js.

The problem is that my rules come at the top of the js file, before all the assetmapper files have been loaded.

### Possible Solution

Generate from yaml first, then custom rules?

Or re-add the placeholders like version 1.0 had

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Spomky**
Target branch: 
Resolves issue # 

- [x] It is a Bug fix
- [x] It is a New feature
- [ ] Breaks BC
- [ ] Includes Deprecations

### CODE REVIEW

**Comment by Spomky** [comment]
This PR should solve several issues.

# Support Range Requests #126

It is possible to enabled the RangeRequestsPlugin.

```yaml
pwa:
    serviceworker:
        enabled: true
        src: "sw.js"
        workbox:
            page_caches:
                - match_callback: 'navigate'
                  range_requests: true
```

# Human-readable Max Age #129

```yaml
pwa:
    serviceworker:
        enabled: true
        src: "sw.js"
        workbox:
            page_caches:
                - match_callback: 'navigate'
                  max_age: 1 year
```

# Better Match Callback Support #125

In the previous version, the bundle used regex to determine the routes. This situation is not confortable in most situations and regular expressions can become difficult to read/write.
The bundle now supports `Match Callback Handlers` and some of them are provided by the bundle.
Note that the key `regex` is not used. Please use `match_callback` instead.

In most situations, the users are not required to write JS callback. This list will evolve in the future.

```yaml
pwa:
    serviceworker:
        enabled: true
        src: "sw.js"
        workbox:
            page_caches:
                - match_callback: 'navigate' # eq to ({request}) => request.mode === 'navigate'
                - match_callback: 'destination: image' # eq to ({request}) => request.destination === 'image'
                - match_callback: 'pathname: /foo/bar.html' # eq to ({url}) => url.pathname === '/foo/bar.html'
                - match_callback: 'pathname: /foo/bar.html' # eq to ({url}) => url.pathname === '/foo/bar.html'
                - match_callback: 'origin: example.com' # eq to ({url}) => url.origin === 'example.com'
                - match_callback: 'endsWith: .foo' # eq to ({url}) => ({url}) => url.pathname.endsWith('.foo')
                - match_callback: 'startsWith: .foo' # eq to ({url}) => ({url}) => url.pathname.startsWith('.foo')
                - match_callback: 'regex: \/foo\/bar\/.*' # eq to new RegExp('\/foo\/bar\/.*')
```

# Default Cache Name

Page caches may have a name. If not defined, a default name will be set.
```yaml
pwa:
    serviceworker:
        enabled: true
        src: "sw.js"
        workbox:
            page_caches:
                - match_callback: 'navigate' # eq to ({request}) => request.mode === 'navigate'
                - match_callback: 'destination: image' # eq to ({request}) => request.destination === 'image'
                  cache_name: 'images'
```

# Rules Organization #132

The rules defined by the bundle are not written before those in the `sw.js` file.

**Comment by tacman** [comment]
Looks good!  I think, though, that routes are going to be more comfortable for Symfony developers.  That is

```yaml
- match_callback: 'route: foo_bar' # eq to ({url}) => url.pathname === '/foo/bar.html'
- match_callback: 'route: article_show' # eq to ({url}) => new RegExp('\/article\/(\d+)\/.*')
```

Since the rules are in javascript, obviously we need to map the routes to the paths, which is what the symfony router service provides.  For routes without parameters, this is pretty straightforward, with parameters a bit more complicated.

I think the way to access the regex is something like this:

```php
// router is injected
public function __construct(private RouterInterface $router){}

public function mapRouteToRegex($routeName = 'app_homepage'): string {

 if ($route = $this->router->getRouteCollection()->get($routeName)) {
    return $route->compile()->getRegex());
}
}
```

I tried to get this working in the CacheWarrmer, but I had some issue and gave up.  I think it had to do with priority services and making sure the routes were loaded first.

**Comment by Spomky** [comment]
> I think, though, that routes are going to be more comfortable for Symfony developers. That is

Good idea. It is now possible.

> - match_callback: 'route: article_show' # eq to ({url}) => new RegExp('\/article\/(\d+)\/.*')

`- match_callback: 'startsWith: /articles/'`  does exactly the same and is much more simpler to me

**Comment by tacman** [comment]
> match_callback: 'startsWith: /articles/' does exactly the same and is much more simpler to me

It doesn't do the exact same thing though.  

In my app, the route 'article_show' matches /article/{id}/show, the pattern /articles matches /articles/list, /articles/browse, /articles/workflow, /articles/about, which may have different caching strategies.  

I think a starting_with regex is too general, symfony programmers are used to routes.

I can understand holding off on implementing it, since it is more complicated (probably building up some gnarly regex), but startWith isn't the same as matching routes.

**Comment by Spomky** [comment]
> It doesn't do the exact same thing though.
> 
> In my app, the route 'article_show' matches /article/{id}/show, the pattern /articles matches /articles/list, /articles/browse, /articles/workflow, /articles/about, which may have different caching strategies.

You are right. In this case `match_callback: 'regex: /article/(\d+)/.*'` is the way to go.

> I can understand holding off on implementing it, since it is more complicated (probably building up some gnarly regex), but startWith isn't the same as matching routes.

Yes and this is the reason why I created an interface so that developers can add (here or in their projects) other possibilities to simplify this. I did that for [`route:`](https://github.com/Spomky-Labs/pwa-bundle/blob/1.1.x/src/MatchCallbackHandler/RouteMatchCallbackHandler.php) you mentioned earlier.
I created a few number of handlers, but use cases are limitless.

**Comment by tacman** [comment]
Ah, great, I'll look into the handler, I'm sure it'll be very useful.

**Pull request merged**
