### PR TITLE
Add new PWA controllers and refactor existing ones

### PR DESCRIPTION
**Pull request by Spomky**
Target branch: 1.3.x
Resolves issue # 

- [ ] It is a Bug fix
- [x] It is a New feature
- [ ] Breaks BC
- [ ] Includes Deprecations

Introduced new controllers for
* badge,
* battery,
* device-orientation,
* fullscreen,
* geolocation,
* vibration
* presentation/receiver

Refactored multiple controllers to extend from a base abstract controller for consistent event dispatching. Updated package.json to include these new controllers with proper webpack configurations.

### CODE REVIEW

**Comment by tacman** [comment]
Very cool! On a related note, what do you think of using the traditional Symfony routing (adding a /config/routing/pwa.yaml file) instead of injecting the routing?  Mostly because it's non-standard to add a Symfony bundle's routes to an application.  It's a bit of a pain, because without a recipe, it's another step.

**Comment by tacman** [comment]
Oops, these are javascript controllers, not Symfony controllers, so I should move that to a new issue.

**Comment by Spomky** [comment]
> On a related note, what do you think of using the traditional Symfony routing

Not sure to clearly understand. The bundle uses the Symfony Router to generate routes so that you can use absolute/relative paths or named routes.
As the bundle itself has no controller, no `/config/routing/*.yaml` is needed.

**Comment by Spomky** [comment]
@mergify queue

**Comment by Spomky** [comment]
@mergify update

**Pull request merged**
