### PR TITLE
fix yaml key (format->type)

### LINKED ISSUE #106: icons command produces invalid yaml file
### Version(s) affected

1.0.x

### Description

As mentioned here: https://github.com/Spomky-Labs/pwa-bundle/discussions/100#discussioncomment-8693164
The command output should be verified

### How to reproduce

Execute the command

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by tacman**
should be type, not format, I believe.  Fixes #106

Target branch: 
Resolves issue # 

- [ ] It is a Bug fix
- [ ] It is a New feature
- [ ] Breaks BC
- [ ] Includes Deprecations

### CODE REVIEW

**Comment by tacman** [comment]
It appears that screenshots and icons have different keys :-(
```yaml
        icons:
          -
            src: icons/icon-1024x1024.png
            sizes:
              - 1024
            type: image/png


        screenshots:
              - src: screenshots/screenshot-1200x1100.png
                width: 1200
                height: 1100
                format: image/png
```

So my PR probably breaks one.  I think the best solution would be to make them consistent names.

**Comment by Spomky** [comment]
Hello. Many thanks. I am AFK with limited access to the Internet. I will have a look at the last issued you raised on Sunday.

**Comment by Spomky** [comment]
Many thanks.
Screenshots use [`type` ](https://developer.mozilla.org/en-US/docs/Web/Manifest/screenshots#type)when icons use [`format`](https://developer.mozilla.org/en-US/docs/Web/Manifest/icons#values).

**Comment by tacman** [comment]
> Screenshots use [type ](https://developer.mozilla.org/en-US/docs/Web/Manifest/screenshots#type)when icons use [format](https://developer.mozilla.org/en-US/docs/Web/Manifest/icons#values).

What's the benefit of that?  There's no 'format' in the docs for either icons or screenshots, only 'type'.

**Comment by Spomky** [comment]
> What's the benefit of that?

This is just a hint for the browser that will use the most suitable icon/screenshot.
I am not sure but e.g. I think Chrome will prefer webp images instead of jpeg or png.

> There's no 'format' in the docs for either icons or screenshots, only 'type'.

I missed that. The documentation is now up to date.

**Comment by tacman** [comment]
No, I mean what's the benefit of having one image key be 'format' and the
other be 'type'?  Are the key values different?  Since we're talking about
the YAML, you could make it consistent and generate whatever the spec says
for the manifest.

**Comment by Spomky** [comment]
OK I understand. I wanted to have key/values in line with the spec. But your remark is legit to me.
To me, type is correct as we are talking about mime type for both properties.

**Pull request merged**
